name = "gai"
version = "0.0.1"
description = "The AI SDK for Gleam. Unified interface for LLM providers."
licences = ["MIT"]

[repository]
type = "github"
user = "chtushar"
repo = "gai"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
